version: '3.8'

services:
  loadbalancer:
    image: yoanbernabeu/simple-load-balancer:latest
    ports:
      - "8080:80"
    environment:
      - DOMAIN_NAME=yourdomain.com
      - EMAIL_ADDRESS=your@email.com
      - BACKEND1_URL=backend1:80
      - BACKEND2_URL=backend2:80
      - ENABLE_HTTPS=false
    depends_on:
      - backend1
      - backend2
    networks:
      - backend-network

  backend1:
    image: yoanbernabeu/simple-load-balancer-demo:latest
    environment:
      - BACKEND_NAME=back1
    networks:
      - backend-network

  backend2:
    image: yoanbernabeu/simple-load-balancer-demo:latest
    environment:
      - BACKEND_NAME=back2
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
